name: Build and deploy Flashcards App on push

on:
  push:
jobs:
  build-and-deploy-flashcards-generator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Clear cache
      working-directory: ./flashcards-generator
      run: rm -rf node_modules && npm cache clean --force
    - name: install dependencies
      working-directory: ./flashcards-generator
      run: npm install
    - name: Run npm build
      working-directory: ./flashcards-generator
      env:
        FLASHCARDS_VAULT_HOSTNAME: ${{ secrets.FLASHCARDS_VAULT_HOSTNAME }}
      run: npm run build
    - name: Setup GCP Login
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH_64 }}
    - name: Gcloud Setup
      run: gcloud config set account ${{ secrets.FLASHCARDS_SERVICE_ACCOUNT }}
    - name: Deploy to gcloud app engine
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH_64 }}
    - run: gcloud app deploy ./flashcards-generator/flashcard-generator.yaml --project ${{ secrets.FLASHCARDS_APP_PROJECT_NAME }}

  build-and-deploy-flashcards-vault:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Clear cache
      working-directory: ./flashcards-vault
      run: rm -rf node_modules && npm cache clean --force
    - name: install dependencies
      working-directory: ./flashcards-vault
      run: npm install
    - name: Run npm build
      working-directory: ./flashcards-vault
      env:
        DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
        FLASHCARDS_VAULT_HOSTNAME: ${{ secrets.DEV_FLASHCARDS_VAULT_HOSTNAME }}
      run: npm run build
    - name: Setup GCP Login
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH_64 }}
    - name: Gcloud Setup
      run: gcloud config set account ${{ secrets.FLASHCARDS_SERVICE_ACCOUNT }}
    - name: Deploy to gcloud app engine
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH_64 }}
    - run : gcloud app deploy ./flashcards-vault/flashcard-vault.yaml --project ${{ secrets.FLASHCARDS_APP_PROJECT_NAME }}
