name: Build and deploy Flashcards Generator on push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: npm install
    - name: Run npm build
      run: npm run build
