name: Build and deploy Flashcards App on push

on:
  push:

jobs:
  build-flashcards-generator:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      working-directory: ./flashcards-generator
      run: npm install
    - name: Run npm build
      working-directory: ./flashcards-generator
      run: npm run build
