name: Build and deploy Flashcards App on push

on:
  push:
    branches:
    - master
jobs:
  build-and-deploy-flashcards-generator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Clear cache
      working-directory: ./flashcards-generator
      run: rm -rf node_modules && npm cache clean --force
    - name: install dependencies
      working-directory: ./flashcards-generator
      run: npm install
    - name: Run npm build
      working-directory: ./flashcards-generator
      env:
        FLASHCARDS_VAULT_HOSTNAME: ${{ secrets.FLASHCARDS_VAULT_HOSTNAME }}
      run: npm run build
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@3.2.1
      with:
        BRANCH: gh-pages
        FOLDER: dist
