name: Build and deploy on push

on: [push]

jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Run npm install
    - uses: actions/checkout@v1
      run: npm install
    - name: Run npm build
      run: npm build
